{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: 1 != 2", "trace": "self = <PyDevPackage.test_demo.TestStringMethods testMethod=test_fail>\n\n    def test_fail(self):\n        \"\"\" This test should fail. \"\"\"\n>       self.assertEqual(1, 2)\nE       AssertionError: 1 != 2\n\ntest_demo.py:16: AssertionError"}, "description": " This test should fail. ", "start": 1696357490567, "stop": 1696357490568, "uuid": "4a7d8dd1-c57e-49ad-bf2b-9bcd7b7eedb8", "historyId": "571d010ca0fcd3a92849e7e7bdf27b23", "testCaseId": "571d010ca0fcd3a92849e7e7bdf27b23", "fullName": "test_demo.TestStringMethods#test_fail", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestStringMethods"}, {"name": "host", "value": "DESKTOP-M8MOJ3U"}, {"name": "thread", "value": "16504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}